version: '3'
services:
  monitoreo:
    build: ./prometheus_monitoreo/prometheus_exporter
    network_mode: "host"
  
  iotbridge:
    build: ./iotbridge
    image: dbracho12/iotbridge:1.1.0
    network_mode: "host"

    env_file:
     - .env

    volumes:
     - /home/logs/iotbridge:/home/logs/iotbridge